# Generated by Django 4.2.1 on 2023-05-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('background_image', models.ImageField(upload_to='images')),
                ('hackathon_image', models.ImageField(upload_to='images')),
                ('submission_type', models.CharField(choices=[('1', 'image'), ('2', 'file'), ('3', 'link')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('submission_image', models.ImageField(upload_to='', verbose_name='submitted')),
                ('submission_file', models.FileField(upload_to='')),
                ('submission_link', models.SlugField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hackathon')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_type', models.CharField(max_length=100)),
                ('monetary_value', models.IntegerField()),
                ('prize_desc', models.TextField(default='')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hackathon')),
            ],
        ),
    ]
